import Products from '@/components/Items'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.scss'
import axios from 'axios'
import ProductCard from '@/components/productCard'
import productDatabase from '../components/productDatabase'


//  The Api that you had given is not working so i used my custom api store Named productDatabase 


// export const  getStaticProps=async ()=>{
//   const res=await axios.get('https://admin.tomedes.com/api/v1/get-reviews?page=1')
//   const apiProductData=  await res.data.data;
//   return{
//     props:{
//       apiProductData,
      
//     },
//   }
// }


export default function Home() {
  return (
    <>
      <Head>
        <title>Bags </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Home section */}


      <div className={styles.home}>

        {/* Products */}
        <div className={styles.itemWrapper} >
          <Products img="/allbags.png" title="All bags" />
          <Products img="/pouch.png" title="Vanity Pouch" />
          <Products img="/tote.png" title="Tote Bag" />
          <Products img="/duffle.png" title="Duffle Bag" />
          <Products img="/laptop.png" title="Laptop Sleeve" />
          <Products img="/messenger.png" title="Messenger Bags" />
          <Products img="/slings.png" title="Slings Bags" />
          <Products img="/handbag.png" title="Hand Bags " />
          <Products img="/bucket.png" title="Bucket " />

        </div>

            {/* Product Title and Cart section */}
            
        <div className={styles.productsection}>
          <div className={styles.productType}><span>Bags</span><div className={styles.dot}></div><span>Backpacks</span></div>
          <div className={styles.productCount}>  <p>13 products</p> <Image src="/arrow.png" width={16.67} height={20}  alt="got to cart"/></div>
        </div>


         {/* Product card section */}
         <div className={styles.cardWrapper}>

            {
            productDatabase.map((elem,index)=>{
                  return(
                    <ProductCard  key={index}  elem={elem} />
                  )
                })
            }
          
         </div>


      </div>
    </>
  )

}

